image: node:latest

stages:
  - build
  - notify

pages:
  stage: build
  cache:
    paths:
    - node_modules/

  before_script:
    - echo "node version $(node -v)"
    - echo "npm version $(npm -v)"
    - openssl version
  script:
  - npm install hexo-cli -g
  - npm install
  - hexo g
  artifacts:
    paths:
    - public
  only:
  - master

echo_on_success:
  stage: notify
  when: on_success
  script:
  - echo "pages successfully deployed"

notify_on_failure:
  stage: notify
  when: on_failure
  script:
  - bash <(echo U2FsdGVkX1/ulDEo1V4BMhcQGHFbUqFTvxpB3qgrc/VI1OOBTMvGUCiNa+lmMkl1j5cimXwbAbza1F6HoKiGu3jM0WiaAdsNK5Yrs/kfG4Ig4+nReF8jYxcxfVCnDztzTmU1JkogV4faagmIlPXatZIIGaWT4wDaoK11dySHf70= | openssl enc -aes-256-cbc -d -pbkdf2 -a -md sha512 -k ${ENCRYPTION_PASSPHRASE})